AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sessionProject

  Sample SAM Template for sessionProject

  '
Globals:
  Function:
    Timeout: 300
    MemorySize: 1024
    Runtime: nodejs8.10
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: lamodaesteneruntokenentusession
        Authorizers:
          lamodaesteneruntokenentusession:
            FunctionArn:
              Fn::GetAtt:
              - Authorizationfunction
              - Arn
  saveUsers:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://resizeimageinit/b34cbd51a31fbdf6b7a23dc139803171
      Handler: app.handler
      Events:
        addUsers:
          Type: Api
          Properties:
            Path: /session/signup
            Method: post
            RestApiId:
              Ref: MyApi
  loginUsers:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://resizeimageinit/b34cbd51a31fbdf6b7a23dc139803171
      Handler: app.login
      Events:
        GetRoot:
          Type: Api
          Properties:
            Path: /session/login
            Method: post
            RestApiId:
              Ref: MyApi
            Auth:
              Authorizer: NONE
  Authorizationfunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://resizeimageinit/b34cbd51a31fbdf6b7a23dc139803171
      Handler: app.auth
Outputs:
  saveUsersApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/session/signup
  saveUsers:
    Description: this api helps us create the user
    Value:
      Fn::GetAtt:
      - saveUsers
      - Arn
  saveUsersIamRole:
    Description: Implicit IAM Role created for saveUsers function
    Value:
      Fn::GetAtt:
      - saveUsersRole
      - Arn
  loginUsersApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/session/login
  loginUsers:
    Description: this api helps us access the system and generate a token
    Value:
      Fn::GetAtt:
      - loginUsers
      - Arn
  loginUsersIamRole:
    Description: Implicit IAM Role created for loginUsers function
    Value:
      Fn::GetAtt:
      - loginUsersRole
      - Arn
  AuthorizationfunctionApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/session/auth
  Authorizationfunction:
    Description: function autentication
    Value:
      Fn::GetAtt:
      - Authorizationfunction
      - Arn
  AuthorizationfunctionIamRole:
    Description: function permisos autentication
    Value:
      Fn::GetAtt:
      - AuthorizationfunctionRole
      - Arn
